# Generated by Django 6.0.6 on 2026-06-26 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
